

# Warning: This is an automatically generated file, do not edit!

srcdir=.
top_srcdir=.

include $(top_srcdir)/config.make

ifeq ($(CONFIG),DEBUG)
ASSEMBLY_COMPILER_COMMAND = dmcs
ASSEMBLY_COMPILER_FLAGS =  -noconfig -codepage:utf8 -warn:2 -optimize- "-nowarn:0168" -debug "-define:DEBUG"
ASSEMBLY = bin/Debug/JavApi.dll
ASSEMBLY_MDB = $(ASSEMBLY).mdb
COMPILE_TARGET = library
PROJECT_REFERENCES = 
BUILD_DIR = bin/Debug/

JAVAPI_DLL_MDB_SOURCE=bin/Debug/JavApi.dll.mdb
JAVAPI_DLL_MDB=$(BUILD_DIR)/JavApi.dll.mdb

endif

ifeq ($(CONFIG),RELEASE)
ASSEMBLY_COMPILER_COMMAND = dmcs
ASSEMBLY_COMPILER_FLAGS =  -noconfig -codepage:utf8 -warn:4 -optimize+ "-nowarn:0168" "-define:TRACE"
ASSEMBLY = bin/Release/JavApi.dll
ASSEMBLY_MDB = 
COMPILE_TARGET = library
PROJECT_REFERENCES = 
BUILD_DIR = bin/Release/

JAVAPI_DLL_MDB=

endif

AL=al
SATELLITE_ASSEMBLY_NAME=$(notdir $(basename $(ASSEMBLY))).resources.dll

PROGRAMFILES = \
	$(JAVAPI_DLL_MDB)  

LINUX_PKGCONFIG = \
	$(JAVAPI_CORE_PC)  


RESGEN=resgen2

JAVAPI_CORE_PC = $(BUILD_DIR)/javapi_core.pc

FILES = \
	biz/ritter/awt/forms/DialogFormsPeer.cs \
	biz/ritter/awt/forms/WindowFormsPeer.cs \
	biz/ritter/net/protocol/http/Handler.cs \
	biz/ritter/net/protocol/http/Connection.cs \
	biz/ritter/io/InputStreamWrapper.cs \
	java/awt/ActiveEvent.cs \
	java/awt/AWTListenerList.cs \
	java/awt/ComponentBehavior.cs \
	java/awt/ComponentOrientation.cs \
	java/awt/Container.cs \
	java/awt/event/HierarchyEvent.cs \
	java/awt/event/HierarchyListener.cs \
	java/awt/event/InputMethodEvent.cs \
	java/awt/event/InputMethodListener.cs \
	java/awt/event/InvocationEvent.cs \
	java/awt/event/ItemEvent.cs \
	java/awt/event/ItemListener.cs \
	java/awt/event/WindowAdapter.cs \
	java/awt/event/WindowStateListener.cs \
	biz/ritter/develop/AssemblyLicense.cs \
	biz/ritter/awt/forms/FormsToolkit.cs \
	biz/ritter/awt/forms/FrameFormPeer.cs \
	biz/ritter/io/StreamWrapper.cs \
	javax/xml/datatype/DatatypeConstants.cs \
	javax/xml/datatype/Duration.cs \
	javax/xml/datatype/XMLGregorianCalendar.cs \
	javax/xml/namespacej/QName.cs \
	javax/xml/transform/Result.cs \
	javax/xml/transform/Source.cs \
	javax/xml/XMLConstants.cs \
	java/awt/color/java.awt.color.CMMException.cs \
	java/awt/color/java.awt.color.ICC_Profile.cs \
	java/awt/color/java.awt.color.ColorSpace.cs \
	java/awt/color/java.awt.color.ICC_ColorSpace.cs \
	java/awt/color/java.awt.color.ICC_ProfileStub.cs \
	java/awt/color/java.awt.color.ProfileDataException.cs \
	java/awt/Component.cs \
	java/awt/Dialog.cs \
	java/awt/event/ComponentEvent.cs \
	java/awt/event/WindowEvent.cs \
	java/awt/event/WindowFocusListener.cs \
	java/awt/event/WindowListener.cs \
	java/awt/font/FontRenderContext.cs \
	java/awt/font/LineMetrics.cs \
	java/awt/font/TextAttribute.cs \
	java/awt/font/TextHitInfo.cs \
	java/awt/font/TransformAttribute.cs \
	java/awt/geom/java.awt.geom.CubicCurve2D.cs \
	java/awt/geom/java.awt.geom.Dimension2D.cs \
	java/awt/geom/java.awt.geom.FlatteningPathIterator.cs \
	java/awt/geom/java.awt.geom.GeneralPath.cs \
	java/awt/geom/java.awt.geom.IllegalPathStateException.cs \
	java/awt/geom/java.awt.geom.Line2D.cs \
	java/awt/geom/java.awt.geom.NoninvertibleTransformException.cs \
	java/awt/geom/java.awt.geom.QuadCurve2D.cs \
	java/awt/geom/java.awt.geom.RectangularShape.cs \
	java/awt/image/AwtImageBackdoorAccessorImpl.cs \
	java/awt/image/BandedSampleModel.cs \
	java/awt/image/ColorModel.cs \
	java/awt/image/ComponentSampleModel.cs \
	java/awt/image/DataBuffer.cs \
	java/awt/image/DataBufferByte.cs \
	java/awt/image/DataBufferDouble.cs \
	java/awt/image/DataBufferFloat.cs \
	java/awt/image/DataBufferInt.cs \
	java/awt/image/DataBufferShort.cs \
	java/awt/image/DataBufferUShort.cs \
	java/awt/image/DirectColorModel.cs \
	java/awt/image/ImageObserver.cs \
	java/awt/image/IndexColorMode.cs \
	java/awt/image/MultiPixelPackedSampleModel.cs \
	java/awt/image/PixelInterleavedSampleModel.cs \
	java/awt/image/Raster.cs \
	java/awt/image/RasterFormatException.cs \
	java/awt/image/SampleModel.cs \
	java/awt/image/SinglePixelPackedSampleModel.cs \
	java/awt/image/WritableRaster.cs \
	java/awt/image/PackedColorModel.cs \
	java/awt/Color.cs \
	java/awt/Dimension.cs \
	java/awt/Font.cs \
	java/awt/Graphics.cs \
	java/awt/ImageObserver.cs \
	java/awt/AWTError.cs \
	java/awt/AWTEvent.cs \
	java/awt/Event.cs \
	java/awt/event/ActionEvent.cs \
	java/awt/event/ActionListener.cs \
	java/awt/Frame.cs \
	java/awt/GraphicsEnvironment.cs \
	java/awt/Image.cs \
	java/awt/ItemSelectable.cs \
	java/awt/Insets.cs \
	java/awt/LayoutManager.cs \
	java/awt/LayoutManager2.cs \
	java/awt/Paint.cs \
	java/awt/PaintContext.cs \
	java/awt/peer/DialogPeer.cs \
	java/awt/peer/WindowPeer.cs \
	java/awt/Point.cs \
	java/awt/Rectangle.cs \
	java/awt/RenderingHints.cs \
	java/awt/Shape.cs \
	java/awt/Toolkit.cs \
	java/awt/geom/java.awt.geom.AffineTransform.cs \
	java/awt/geom/java.awt.geom.PathIterator.cs \
	java/awt/geom/java.awt.geom.Point2D.cs \
	java/awt/geom/java.awt.geom.Rectangle2D.cs \
	java/awt/image/BufferedImage.cs \
	java/awt/Transparency.cs \
	java/awt/Window.cs \
	java/beans/ExceptionListener.cs \
	java/beans/IndexedPropertyChangeEvent.cs \
	java/beans/PropertyChangeEvent.cs \
	java/beans/PropertyChangeListener.cs \
	java/beans/PropertyChangeListenerProxy.cs \
	java/beans/PropertyChangeSupport.cs \
	java/beans/VetoableChangeListener.cs \
	java/beans/Visibility.cs \
	java/io/BufferedWriter.cs \
	java/io/FileNotFoundException.cs \
	java/io/FileReader.cs \
	java/io/FileWriter.cs \
	java/io/PipedInputStream.cs \
	java/io/PipedOutputStream.cs \
	java/io/PrintStream.cs \
	java/lang/ClassLoader.cs \
	java/lang/OutOfMemoryError.cs \
	java/lang/reflect/Array.cs \
	java/lang/reflect/Constructor.cs \
	java/lang/reflect/InvocationTargetException.cs \
	java/lang/reflect/Method.cs \
	java/lang/reflect/Modifiers.cs \
	java/lang/ThreadDeath.cs \
	java/lang/ThreadLocal.cs \
	java/lang/reflect/AccessibleObject.cs \
	java/lang/RuntimePermission.cs \
	java/lang/SecurityManager.cs \
	java/lang/SystemJ.cs \
	java/net/InetAddress.cs \
	java/net/MalformedURLException.cs \
	java/net/NetPermission.cs \
	java/net/Proxy.cs \
	java/net/UnknownHostException.cs \
	java/net/URLConnection.cs \
	java/net/URLStreamHandler.cs \
	java/net/URLStreamHandlerFactory.cs \
	java/security/AccessController.cs \
	java/security/AllPermission.cs \
	java/security/AllPermissionCollection.cs \
	java/security/BasicPermission.cs \
	java/security/BasicPermissionCollection.cs \
	java/security/Certificate.cs \
	java/security/cert/java.security.cert.Certificate.cs \
	java/awt/peer/FramePeer.cs \
	java/beans/Introspector.cs \
	java/beans/BeanDescriptor.cs \
	java/beans/BeanInfo.cs \
	java/beans/EventSetDescriptor.cs \
	java/beans/FeatureDescriptor.cs \
	java/beans/IntrospectionException.cs \
	java/beans/MethodDescriptor.cs \
	java/beans/PropertyDescriptor.cs \
	java/beans/SimpleBeanInfo.cs \
	java/beans/StandardBeanInfo.cs \
	java/io/LineNumberReader.cs \
	java/io/StringWriter.cs \
	java/lang/Byte.cs \
	java/lang/Class.cs \
	java/lang/NoSuchMethodException.cs \
	java/lang/Short.cs \
	java/lang/StackTraceElement.cs \
	java/lang/Void.cs \
	java/security/CodeSource.cs \
	java/security/DigestException.cs \
	java/security/GeneralSecurityException.cs \
	java/security/Guard.cs \
	java/security/InvalidParameterException.cs \
	java/security/MessageDigest.cs \
	java/security/MessageDigestSpi.cs \
	java/security/NoSuchAlgorithmException.cs \
	java/security/NuSuchProviderException.cs \
	java/security/Permission.cs \
	java/security/PermissionCollection.cs \
	java/security/PermissionHash.cs \
	java/security/Permissions.cs \
	java/security/Policy.cs \
	java/security/PolicySpi.cs \
	java/security/PrivilegedAction.cs \
	java/security/ProtectionDomain.cs \
	java/security/Provider.cs \
	java/security/Security.cs \
	java/security/SecurityPermission.cs \
	java/security/UnresolvedPermission.cs \
	java/security/UnresolvedPermissionCollection.cs \
	java/io/NotActiveException.cs \
	java/io/NotSerializableException.cs \
	java/lang/Package.cs \
	java/sql/Array.cs \
	java/sql/Blob.cs \
	java/sql/CallableStatement.cs \
	java/sql/ClientInfoStatus.cs \
	java/sql/Clob.cs \
	java/sql/Connection.cs \
	java/sql/DatabaseMetaData.cs \
	java/sql/Date.cs \
	java/sql/Driver.cs \
	java/sql/DriverManager.cs \
	java/sql/DriverPropertyInfo.cs \
	java/sql/NClob.cs \
	java/sql/ParameterMetaData.cs \
	java/sql/PreparedStatement.cs \
	java/sql/Ref.cs \
	java/sql/ResultSet.cs \
	java/sql/ResultSetMetaData.cs \
	java/sql/RowId.cs \
	java/sql/RowIdLifetime.cs \
	java/sql/Savepoint.cs \
	java/sql/SQLClientInfoException.cs \
	java/sql/SQLException.cs \
	java/sql/SQLFeatureNotSupportedException.cs \
	java/sql/SQLNonTransientConnectionException.cs \
	java/sql/SQLNonTransientException.cs \
	java/sql/SQLPermission.cs \
	java/sql/SQLWarning.cs \
	java/sql/SQLXML.cs \
	java/sql/Statement.cs \
	java/sql/Struct.cs \
	java/sql/Time.cs \
	java/sql/Timestamp.cs \
	java/sql/Types.cs \
	java/sql/Wrapper.cs \
	java/text/NumberFormat.cs \
	java/text/SimpleDateFormat.cs \
	java/text/spi/NumberFormatProvider.cs \
	java/text/StringCharacterIterator.cs \
	java/util/concurrent/lockj/java.util.concurrent.lock.ReentrantLock.cs \
	java/util/BitSet.cs \
	java/util/concurrent/java.util.concurrent.ConcurrentMap.cs \
	java/util/concurrent/java.util.concurrent.ConcurrentNavigableMap.cs \
	java/util/DuplicateFormatFlagsExceptions.cs \
	java/util/FormatFlagConversionMismatchException.cs \
	java/util/Formattable.cs \
	java/util/FormattableFlags.cs \
	java/util/regex/Pattern.cs \
	java/util/_Formatter.cs \
	java/util/TimeZone.cs \
	java/util/FormatterClosedException.cs \
	java/util/IllegalFormatCodePointException.cs \
	java/util/IllegalFormatConversationException.cs \
	java/util/IllegalFormatException.cs \
	java/io/BufferedOutputStream.cs \
	java/io/PrintWriter.cs \
	java/io/DataInputStream.cs \
	java/io/DataOutputStream.cs \
	java/io/ObjectInputStream.cs \
	java/io/ObjectOutputStream.cs \
	java/io/UTFDataFormatException.cs \
	java/lang/AbstractStringBuilder.cs \
	java/lang/annotation/java.lang.annotation.Annotation.cs \
	java/lang/AssertionError.cs \
	java/lang/Boolean.cs \
	java/lang/Deprecated.cs \
	java/lang/IllegalAccessException.cs \
	java/lang/InstantiationException.cs \
	java/lang/LinkageError.cs \
	java/lang/NegativeArraySizeException.cs \
	java/lang/NoClassDefFoundError.cs \
	java/lang/ref/java.lang.refj.SoftReference.cs \
	java/lang/StringBuffer.cs \
	java/lang/StringBuilder.cs \
	java/text/AttributedCharacterIterator.cs \
	java/dotnet/dotnet.nio.charset.CharsetProviderImpl.cs \
	java/dotnet/dotnet.util.wrapper.EnumeratorWrapper.cs \
	java/dotnet/dotnet.util.wrapper.InputStreamWrapper.cs \
	java/dotnet/dotnet.util.wrapper.EnumerableIterator.cs \
	java/dotnet/dotnet.util.wrapper.StreamInputWrapper.cs \
	java/io/BufferedInputStream.cs \
	java/io/ByteArrayInputStream.cs \
	java/io/ByteArrayOutputStream.cs \
	java/io/EOFException.cs \
	java/io/InputStreamReader.cs \
	java/io/InterruptedIOException.cs \
	java/io/RandomAccessFile.cs \
	java/io/StreamTokenizer.cs \
	java/lang/ArithmeticException.cs \
	java/lang/Character.cs \
	java/lang/ClassCastException.cs \
	java/lang/Double.cs \
	java/lang/Error.cs \
	java/lang/Float.cs \
	java/lang/IllegalMonitorStateException.cs \
	java/lang/InternalError.cs \
	java/lang/InterruptedException.cs \
	java/lang/NumberFormatException.cs \
	java/lang/ref/java.lang.refj.ReferenceQueue.cs \
	java/lang/ref/java.lang.refj.Reference.cs \
	java/lang/ref/java.lang.refj.WeakReference.cs \
	java/lang/VirtualMachineError.cs \
	java/math/BigDecimal.cs \
	java/math/BigInteger.cs \
	java/math/BitLevel.cs \
	java/math/Conversion.cs \
	java/math/Division.cs \
	java/math/Elementary.cs \
	java/math/Logical.cs \
	java/math/MathContext.cs \
	java/math/Multiplication.cs \
	java/math/Primality.cs \
	java/math/RoundingMode.cs \
	java/net/URIEncoderDecoder.cs \
	java/net/URISyntaxException.cs \
	java/net/URL.cs \
	java/nio/charset/java.nio.charset.CharacterCodingException.cs \
	java/nio/charset/java.nio.charset.Charset.cs \
	java/nio/charset/java.nio.charset.CharsetDecoder.cs \
	java/nio/charset/java.nio.charset.CharsetEncoder.cs \
	java/nio/charset/java.nio.charset.CoderMalfunctionError.cs \
	java/nio/charset/java.nio.charset.CoderResult.cs \
	java/nio/charset/java.nio.charset.CodingErrorAction.cs \
	java/nio/charset/java.nio.charset.IllegalCharsetNameException.cs \
	java/nio/charset/java.nio.charset.MalformedInputException.cs \
	java/nio/charset/spi/java.nio.charset.spi.CharsetProvider.cs \
	java/nio/charset/java.nio.charset.UnmappableCharacterException.cs \
	java/nio/charset/java.nio.charset.UnsupportedCharsetException.cs \
	java/security/Key.cs \
	java/security/PublicKey.cs \
	java/text/AttributedString.cs \
	java/text/CharacterIterator.cs \
	java/text/FieldPosition.cs \
	java/text/Format.cs \
	java/text/ParseException.cs \
	java/text/ParsePosition.cs \
	java/util/AbstractCollection.cs \
	java/nio/java.nio.CharArrayBuffer.cs \
	java/nio/java.nio.CharSequenceAdapter.cs \
	java/io/FilterReader.cs \
	java/io/BufferedReader.cs \
	java/io/PushbackReader.cs \
	java/io/Reader.cs \
	java/lang/Integer.cs \
	java/lang/Iterable.cs \
	java/lang/Long.cs \
	java/lang/Readable.cs \
	java/net/BindException.cs \
	java/net/ServerSocket.cs \
	java/net/SocketException.cs \
	java/net/SocketInputStream.cs \
	java/io/Closeable.cs \
	java/io/DataInput.cs \
	java/io/DataOutput.cs \
	java/io/Externalizable.cs \
	java/io/File.cs \
	java/io/FileDescriptor.cs \
	java/io/FileFilter.cs \
	java/io/FileInputStream.cs \
	java/io/FilenameFilter.cs \
	java/io/FileOutputStream.cs \
	java/io/FilterInputStream.cs \
	java/io/FilterOutputStream.cs \
	java/io/Flushable.cs \
	java/io/InputStream.cs \
	java/io/InvalidObjectException.cs \
	java/io/IOException.cs \
	java/io/ObjectInput.cs \
	java/io/ObjectInputValidation.cs \
	java/io/ObjectOutput.cs \
	java/io/ObjectStreamConstants.cs \
	java/io/ObjectStreamException.cs \
	java/io/OutputStream.cs \
	java/io/OutputStreamWriter.cs \
	java/io/PushbackInputStream.cs \
	java/io/Serializable.cs \
	java/io/UnsupportedEncodingException.cs \
	java/io/Writer.cs \
	java/lang/Appendable.cs \
	java/lang/ArrayIndexOutOfBoundsException.cs \
	java/lang/ArrayStoreException.cs \
	java/lang/CharSequence.cs \
	java/lang/ClassNotFoundException.cs \
	java/lang/Cloneable.cs \
	java/lang/CloneNotSupportedException.cs \
	java/lang/Comparable.cs \
	java/lang/Exception.cs \
	java/lang/IllegalArgumentException.cs \
	java/lang/IllegalStateException.cs \
	java/lang/IllegalThreadStateException.cs \
	java/lang/IndexOutOfBoundsException.cs \
	java/lang/Math.cs \
	java/lang/NullPointerException.cs \
	java/lang/Number.cs \
	java/lang/Process.cs \
	java/lang/ReflectiveOperationException.cs \
	java/lang/Runnable.cs \
	java/lang/Runtime.cs \
	java/lang/RuntimeException.cs \
	java/lang/SecurityException.cs \
	java/lang/StringIndexOutOfBoundsException.cs \
	java/lang/StringJ.cs \
	java/lang/Thread.cs \
	java/lang/Throwable.cs \
	java/lang/UnsupportedOperationException.cs \
	java/net/Socket.cs \
	java/net/SocketOutputStream.cs \
	java/net/URI.cs \
	java/nio/java.nio.BufferFactory.cs \
	java/nio/java.nio.BufferOverflowException.cs \
	java/nio/java.nio.BufferUnderflowException.cs \
	java/nio/java.nio.ByteBuffer.cs \
	java/nio/java.nio.ByteOrder.cs \
	java/nio/java.nio.CharBuffer.cs \
	java/nio/java.nio.HeapByteBuffer.cs \
	java/nio/java.nio.InvalidMarkException.cs \
	java/nio/java.nio.ReadOnlyBufferException.cs \
	java/nio/java.nio.ReadOnlyHeapByteBuffer.cs \
	java/nio/java.nio.ReadWriteCharArrayBuffer.cs \
	java/nio/java.nio.ReadWriteHeapByteBuffer.cs \
	java/util/AbstractList.cs \
	java/util/AbstractMap.cs \
	java/util/AbstractSequentialList.cs \
	java/util/AbstractSet.cs \
	java/util/ArrayList.cs \
	java/util/Calendar.cs \
	java/util/Collection.cs \
	java/util/Collections.cs \
	java/util/Comparator.cs \
	java/util/concurrent/java.util.concurrent.Callable.cs \
	java/util/ConcurrentModificationException.cs \
	java/util/Currency.cs \
	java/util/Date.cs \
	java/util/Deque.cs \
	java/util/Dictionary.cs \
	java/util/EmptyStackException.cs \
	java/util/Enumeration.cs \
	java/util/EventListener.cs \
	java/util/EventListenerProxy.cs \
	java/util/EventObject.cs \
	java/util/GregorianCalendar.cs \
	java/util/HashMap.cs \
	java/util/HashSet.cs \
	java/util/Hashtable.cs \
	java/util/IllegalFormatFlagsException.cs \
	java/util/IllegalFormatPrecisionException.cs \
	java/util/IllegalFormatWidthException.cs \
	java/util/Iterator.cs \
	java/util/jar/java.util.jar.Attributes.cs \
	java/util/jar/java.util.jar.InitManifest.cs \
	java/util/jar/java.util.jar.JarEntry.cs \
	java/util/jar/java.util.jar.JarFile.cs \
	java/util/jar/java.util.jar.JarVerifier.cs \
	java/util/jar/java.util.jar.Manifest.cs \
	java/util/LinkedHashSet.cs \
	java/util/LinkedList.cs \
	java/util/List.cs \
	java/util/ListIterator.cs \
	java/util/Locale.cs \
	java/util/Map.cs \
	java/util/MapEntry.cs \
	java/util/MissingFormatWidthException.cs \
	java/util/MissingResourceException.cs \
	java/util/NavigableMap.cs \
	java/util/NavigableSet.cs \
	java/util/NoSuchElementException.cs \
	java/util/Observable.cs \
	java/util/Observer.cs \
	java/util/Queue.cs \
	java/util/Random.cs \
	java/util/RandomAccess.cs \
	java/util/ResourceBundle.cs \
	java/util/Set.cs \
	java/util/SortedMap.cs \
	java/util/SortedSet.cs \
	java/util/Stack.cs \
	java/util/StringTokenizer.cs \
	java/util/Timer.cs \
	java/util/TimerTask.cs \
	java/util/TreeMap.cs \
	java/util/TreeSet.cs \
	java/util/UnknownFormatConversationException.cs \
	java/util/Vector.cs \
	Kajabity/Tools/Java/JavaPropertyReader.cs \
	Kajabity/Tools/Java/JavaPropertyWriter.cs \
	org/apache/harmony/awt/gl/MultiRectArea.cs \
	org/apache/harmony/awt/gl/MultiRectAreaOp.cs \
	org/apache/harmony/awt/ListenerList.cs \
	org/apache/harmony/awt/ReadOnlyIterator.cs \
	org/apache/harmony/awt/state/MenuItemState.cs \
	org/apache/harmony/luni/util/PriviAction.cs \
	org/apache/harmony/luni/TwoKeyHashMap.cs \
	java/util/zip/java.util.zip.Adler32.cs \
	java/util/zip/java.util.zip.CheckedInputStream.cs \
	java/util/zip/java.util.zip.CheckedOutputStream.cs \
	java/util/zip/java.util.zip.Checksum.cs \
	java/util/zip/java.util.zip.CRC32.cs \
	java/util/zip/java.util.zip.DataFormatException.cs \
	java/util/zip/java.util.zip.Deflater.cs \
	java/util/zip/java.util.zip.DeflaterInputStream.cs \
	java/util/zip/java.util.zip.Inflater.cs \
	java/util/zip/java.util.zip.InflaterInputStream.cs \
	java/util/zip/java.util.zip.DeflaterOutputStream.cs \
	java/util/zip/java.util.zip.GZIPInputStream.cs \
	java/util/zip/java.util.zip.GZIPOutputStream.cs \
	java/util/Properties.cs \
	java/util/zip/java.util.zip.InflaterOutputStream.cs \
	java/util/zip/java.util.zip.ZipEntry.cs \
	java/util/zip/java.util.zip.ZipError.cs \
	java/util/zip/java.util.zip.ZipException.cs \
	java/util/Arrays.cs \
	java/io/ReadOnlyCharArrayBuffer.cs \
	java/util/LinkedHashMap.cs \
	java/util/zip/java.util.zip.ZipFile.cs \
	java/util/zip/java.util.zip.ZipInputStream.cs \
	java/util/zip/java.util.zip.ZipOutputStream.cs \
	java/util/MissingFormatArgumentException.cs \
	org/apache/harmony/archive/util/Util.cs \
	org/apache/harmony/awt/gl/color/ColorScaler.cs \
	org/apache/harmony/awt/gl/color/ICC_Transform.cs \
	org/apache/harmony/awt/gl/color/LTUColorConverter.cs \
	org/apache/harmony/awt/gl/color/ColorConverter.cs \
	org/apache/harmony/awt/gl/image/DataBufferListener.cs \
	org/apache/harmony/awt/gl/image/OrdinaryWritableRaster.cs \
	org/apache/harmony/awt/gl/AwtImageBackdoorAccessor.cs \
	org/apache/harmony/awt/gl/Crossing.cs \
	org/apache/harmony/awt/gl/Surface.cs \
	org/apache/harmony/awt/Utils.cs \
	org/apache/harmony/luni/util/BinarySearch.cs \
	org/apache/harmony/luni/util/InputStreamHelper.cs \
	org/apache/harmony/luni/util/Util.cs \
	org/apache/harmony/luni/util/URLUtil.cs \
	org/apache/harmony/misc/HashCode.cs \
	org/apache/harmony/security/fortress/DefaultPolicy.cs \
	org/apache/harmony/security/fortress/Engine.cs \
	org/apache/harmony/security/fortress/PolicyUtils.cs \
	org/apache/harmony/security/fortress/SecurityAccess.cs \
	org/apache/harmony/security/fortress/Services.cs \
	org/apache/harmony/security/Util.cs \
	org/xml/sax/ext/org.xml.sax.ext.Attributes2.cs \
	org/xml/sax/ext/org.xml.sax.ext.Attributes2Impl.cs \
	org/xml/sax/ext/org.xml.sax.ext.DeclHandler.cs \
	org/xml/sax/ext/org.xml.sax.ext.DefaultHandler2.cs \
	org/xml/sax/ext/org.xml.sax.ext.EntityResolver2.cs \
	org/xml/sax/ext/org.xml.sax.ext.LexicalHandler1.cs \
	org/xml/sax/ext/org.xml.sax.ext.Locator2.cs \
	org/xml/sax/ext/org.xml.sax.ext.Locator2Impl.cs \
	org/xml/sax/helpers/XMLReaderAdapter.cs \
	org/xml/sax/InputSource.cs \
	org/xml/sax/AttributeList.cs \
	org/xml/sax/Attributes.cs \
	org/xml/sax/ContentHandler.cs \
	org/xml/sax/DocumentHandler.cs \
	org/xml/sax/DTDHandler.cs \
	org/xml/sax/EntityResolver.cs \
	org/xml/sax/ErrorHandler.cs \
	org/xml/sax/HandlerBase.cs \
	org/xml/sax/Locator.cs \
	org/xml/sax/Parser.cs \
	org/xml/sax/SAXException.cs \
	org/xml/sax/SAXNotRecognizedException.cs \
	org/xml/sax/SAXNotSupportedException.cs \
	org/xml/sax/XMLFilter.cs \
	org/xml/sax/XMLReader.cs \
	org/xml/sax/SAXParseException.cs \
	System/JavaExtensions.cs \
	java/dotnet/dotnet.util.wrapper.OutputStreamWrapper.cs \
	Properties/AssemblyInfo.cs \
	java/util/spi/CurrencyNameProvider.cs \
	java/util/spi/LocaleNameProvider.cs \
	java/util/spi/LocaleServiceProvider.cs \
	java/util/spi/TimeZoneNameProvider.cs \
	java/util/prefs/BackingStoreException.cs \
	java/util/prefs/InvalidPreferencesFormatException.cs \
	java/util/prefs/NodeChangeEvent.cs \
	java/util/prefs/NodeChangeListener.cs \
	java/util/prefs/PreferenceChangeEvent.cs \
	java/util/prefs/PreferenceChangeListener.cs \
	java/util/prefs/Preferences.cs \
	java/util/prefs/PreferencesFactory.cs \
	java/util/SimpleTimeZone.cs \
	java/util/TimeZones.cs \
	java/util/TooManyListenersException.cs \
	java/nio/Buffer.cs \
	java/lang/AbstractMethodError.cs \
	java/lang/ClassCircularityError.cs \
	java/lang/ClassFormatError.cs \
	java/lang/InstantiationError.cs \
	java/lang/IncompatibleClassChangeError.cs \
	java/lang/NoSuchFieldError.cs \
	java/lang/NoSuchFieldException.cs \
	java/lang/NoSuchMethodError.cs \
	java/lang/ProcessBuilder.cs \
	java/lang/StackOverflowError.cs \
	java/lang/StrictMath.cs \
	java/lang/VerifyError.cs \
	java/lang/TypeNotPresentException.cs \
	java/lang/UnknownError.cs \
	java/lang/UnsatisfiedLinkError.cs \
	java/lang/UnsupportedClassVersionError.cs \
	java/lang/AutoCloseable.cs \
	java/io/IOError.cs \
	java/io/WriteAbortedException.cs \
	java/io/SyncFailedException.cs \
	java/io/StringReader.cs \
	java/io/StringBufferInputStream.cs \
	java/io/StreamCorruptedException.cs \
	java/io/SerializablePermission.cs \
	java/io/SequenceInputStream.cs \
	java/io/PipedWriter.cs \
	java/io/PipedReader.cs \
	java/io/OptionalDataException.cs \
	java/io/LineNumberInputStream.cs \
	java/io/InvalidClassException.cs \
	java/io/CharArrayReader.cs \
	java/io/CharArrayWriter.cs \
	java/io/CharConversionException.cs \
	java/io/FilePermission.cs \
	java/io/FilePermissionCollection.cs \
	org/xml/sax/helpers/AttributeListImpl.cs \
	org/xml/sax/helpers/DefaultHandler.cs \
	org/xml/sax/helpers/LocatorImpl.cs \
	org/xml/sax/helpers/NamespaceSupport.cs \
	org/xml/sax/helpers/NewInstance.cs \
	org/xml/sax/helpers/ParserAdapter.cs \
	org/xml/sax/helpers/ParserFactory.cs \
	org/xml/sax/helpers/XMLFilterImpl.cs \
	org/xml/sax/helpers/XMLReaderFactory.cs \
	org/xml/sax/helpers/AttributesImpl.cs \
	javax/xml/crypto/KeySelectorException.cs \
	javax/xml/crypto/Data.cs \
	java/security/spec/AlgorithmParameterSpec.cs \
	javax/xml/crypto/AlgorithmMethod.cs \
	javax/xml/crypto/NodeSetData.cs \
	javax/xml/crypto/OctetStreamData.cs \
	javax/xml/crypto/URIReference.cs \
	javax/xml/crypto/URIDereferencer.cs \
	javax/xml/crypto/XMLCryptoContext.cs \
	javax/xml/crypto/KeySelector.cs \
	javax/xml/crypto/KeySelectorResult.cs \
	javax/xml/crypto/dsig/keyinfo/KeyInfo.cs \
	javax/xml/crypto/XMLStructure.cs \
	javax/xml/crypto/dsig/TransformException.cs \
	javax/xml/crypto/dsig/spec/TransformParameterSpec.cs \
	javax/xml/crypto/dsig/Transform.cs \
	javax/xml/crypto/dsig/TransformConstants.cs \
	javax/xml/crypto/dsig/keyinfo/RetrievalMethod.cs \
	javax/xml/crypto/URIReferenceException.cs \
	javax/xml/crypto/dsig/XMLSignatureException.cs \
	java/lang/_PrintStream.cs \
	javax/xml/crypto/dsig/XMLSignature.cs \
	javax/xml/crypto/dsig/XMLSignatureConstants.cs \
	javax/xml/crypto/dsig/XMLValidateContext.cs \
	javax/xml/crypto/dsig/SignedInfo.cs \
	javax/xml/crypto/dsig/XMLSignContext.cs \
	javax/xml/crypto/dsig/SignatureMethod.cs \
	javax/xml/crypto/dsig/SignatureMethodConstants.cs \
	javax/xml/crypto/dsig/CanonicalizationMethod.cs \
	javax/xml/crypto/dsig/CanonicalizationMethodeConstants.cs \
	javax/xml/crypto/dsig/XMLSignatureFactory.cs \
	javax/xml/crypto/dsig/Reference.cs \
	javax/xml/crypto/dsig/DigestMethod.cs \
	javax/xml/crypto/dsig/XMLObjectConstants.cs \
	javax/xml/crypto/dsig/XMLObject.cs \
	javax/xml/crypto/dsig/Manifest.cs \
	javax/xml/crypto/dsig/ManifestConstants.cs \
	javax/xml/crypto/dsig/SignatureProperty.cs \
	javax/xml/crypto/dsig/SignatureProperties.cs \
	javax/xml/crypto/SignaturePropertiesConstants.cs \
	javax/xml/crypto/dsig/DigestMethodConstants.cs \
	javax/xml/crypto/dsig/spec/DigestMethodParameterSpec.cs \
	javax/xml/crypto/dsig/spec/SignatureMethodParameterSpec.cs \
	javax/xml/crypto/dsig/spec/C14NMethodParameterSpec.cs \
	javax/xml/crypto/dsig/keyinfo/KeyInfoFactory.cs \
	javax/xml/crypto/dsig/keyinfo/KeyName.cs \
	javax/xml/crypto/dsig/keyinfo/KeyValue.cs \
	javax/xml/crypto/dsig/keyinfo/KeyValueConstants.cs \
	javax/xml/crypto/dsig/keyinfo/PGPData.cs \
	javax/xml/crypto/dsig/keyinfo/PGPDataConstants.cs \
	javax/xml/crypto/dsig/keyinfo/X509Data.cs \
	javax/xml/crypto/dsig/keyinfo/X509DataConstants.cs \
	javax/xml/crypto/dsig/keyinfo/X509IssuerSerial.cs \
	javax/xml/crypto/NoSuchMechanismException.cs \
	javax/xml/crypto/MarshalException.cs \
	javax/xml/crypto/dsig/spec/ExcC14NParameterSpec.cs \
	javax/xml/crypto/dsig/spec/HMACParameterSpec.cs \
	javax/xml/crypto/dsig/spec/XPathType.cs \
	javax/xml/crypto/dsig/spec/XPathFilterParameterSpec.cs \
	javax/xml/crypto/dsig/spec/XPathFilter2ParameterSpec.cs \
	javax/xml/crypto/dsig/spec/XSLTTransformParameterSpec.cs \
	javax/xml/crypto/dsig/TransformService.cs \
	org/w3c/dom/Attr.cs \
	org/w3c/dom/CDATASection.cs \
	org/w3c/dom/CharacterData.cs \
	org/w3c/dom/Comment.cs \
	org/w3c/dom/Document.cs \
	org/w3c/dom/DocumentFragment.cs \
	org/w3c/dom/DocumentType.cs \
	org/w3c/dom/DOMConfiguration.cs \
	org/w3c/dom/DOMError.cs \
	org/w3c/dom/DOMErrorHandler.cs \
	org/w3c/dom/DOMException.cs \
	org/w3c/dom/DOMImplementation.cs \
	org/w3c/dom/DOMImplementationList.cs \
	org/w3c/dom/DOMImplementationSource.cs \
	org/w3c/dom/DOMLocator.cs \
	org/w3c/dom/DOMStringList.cs \
	org/w3c/dom/Element.cs \
	org/w3c/dom/ElementTraversal.cs \
	org/w3c/dom/Entity.cs \
	org/w3c/dom/EntityReference.cs \
	org/w3c/dom/NamedNodeMap.cs \
	org/w3c/dom/NameList.cs \
	org/w3c/dom/Node.cs \
	org/w3c/dom/NodeList.cs \
	org/w3c/dom/Notation.cs \
	org/w3c/dom/ProcessingInstruction.cs \
	org/w3c/dom/Text.cs \
	org/w3c/dom/TypeInfo.cs \
	org/w3c/dom/UserDataHandler.cs \
	javax/xml/crypto/dsig/dom/DOMSignContext.cs \
	javax/xml/crypto/dsig/dom/DOMValidateContext.cs \
	javax/xml/crypto/dom/DOMURIReference.cs \
	javax/xml/crypto/dom/DOMStructure.cs \
	javax/xml/crypto/dom/DOMCryptoContext.cs \
	java/util/logging/Filter.cs \
	java/util/logging/Handler.cs \
	java/util/logging/Level.cs \
	java/util/logging/Logger.cs \
	java/util/logging/LogManager.cs \
	java/util/logging/LogRecord.cs \
	java/util/logging/ErrorManager.cs \
	java/util/logging/StreamHandler.cs \
	java/util/logging/Formatter.cs \
	java/text/MessageFormat.cs \
	java/util/logging/ConsoleHandler.cs \
	java/util/logging/SimpleFormatter.cs \
	java/util/logging/MemoryHandler.cs \
	java/util/logging/FileHandler.cs \
	java/nio/channels/FileLock.cs \
	java/nio/channels/FileChannel.cs \
	java/util/logging/LoggingPermission.cs \
	java/util/logging/LoggingMXBean.cs \
	java/util/InputMismatchException.cs \
	java/util/InvalidPropertiesFormatException.cs \
	java/util/ServiceConfigurationError.cs \
	java/util/UnknownFormatFlagsException.cs \
	java/security/SecureRandomSpi.cs \
	java/dotnet/lang/ConsoleErrorStream.cs \
	java/dotnet/lang/ConsoleInputStream.cs \
	java/dotnet/lang/ConsoleOutputPrintStream.cs \
	java/dotnet/lang/Operator.cs \
	javax/imageio/ImageIO.cs \
	javax/imageio/spi/ServiceRegistry.cs \
	javax/imageio/spi/RegisterableService.cs 

DATA_FILES = 

RESOURCES = 

EXTRAS = \
	java/awt/event/InputEvent.txt \
	java/awt/event/KeyAdapter.txt \
	java/awt/event/KeyEvent.txt \
	java/awt/event/KeyListener.txt \
	java/awt/event/MouseAdapter.txt \
	java/awt/event/MouseEvent.txt \
	java/awt/event/MouseListener.txt \
	java/text/BreakIterator.java \
	java/text/ChoiceFormat.cs.txt \
	java/text/CollationKey.cs.txt \
	java/text/Collator.cs.txt \
	java/text/DateFormatSymbols.cs.txt \
	java/text/MessageFormat.cs.txt \
	java/text/spi/BreakIteratorProvider.java \
	java/text/spi/CollatorProvider.java \
	java/text/spi/DateFormatProvider.java \
	java/text/spi/DateFormatSymbolsProvider.java \
	java/text/spi/DecimalFormatSymbolsProvider.java \
	java/util/concurrent/java.util.concurrent.CopyOnWriteArrayList.txt \
	org/apache/harmony/awt/state/MenuBarState.txt \
	org/apache/harmony/awt/state/MenuState.txt \
	CHANGES \
	TODO \
	java/io/SerialUIDCalculator.cs \
	java/security/SecureRandom\ (Kopie).cs \
	java/util/UUID.cs.java \
	javax/imageio/spi/IIORegistry.java \
	javax/imageio/spi/IIOServiceProvider.java \
	javax/imageio/spi/ImageInputStreamSpi.java \
	javax/imageio/spi/ImageOutputStreamSpi.java \
	javax/imageio/spi/ImageReaderSpi.java \
	javax/imageio/spi/ImageReaderWriterSpi.java \
	javax/imageio/spi/ImageTranscoderSpi.java \
	javax/imageio/spi/ImageWriterSpi.java \
	javax/xml/crypto \
	java/security/spec \
	javax/xml/crypto/dsig \
	javax/xml/crypto/dsig/keyinfo \
	javax/xml/crypto/dsig/spec \
	javax/xml/crypto/dsig/dom \
	org/w3c \
	org/w3c/dom \
	org/w3c/dom/.svn \
	javax/xml/crypto/dom \
	java/nio/channels \
	java/dotnet/lang \
	javax/imageio/spi \
	javapi_core.pc.in 

REFERENCES =  \
	System \
	System.Core \
	System.Numerics \
	System.Windows.Forms \
	System.Xaml \
	System.Xml.Linq \
	System.Data.DataSetExtensions \
	Microsoft.CSharp \
	System.Data \
	System.Xml \
	WindowsBase

DLL_REFERENCES = 

CLEANFILES = $(PROGRAMFILES) $(LINUX_PKGCONFIG) 

#Targets
all-local: $(ASSEMBLY) $(PROGRAMFILES) $(LINUX_PKGCONFIG)  $(top_srcdir)/config.make



$(eval $(call emit-deploy-wrapper,JAVAPI_CORE_PC,javapi_core.pc))


$(eval $(call emit_resgen_targets))
$(build_xamlg_list): %.xaml.g.cs: %.xaml
	xamlg '$<'


$(ASSEMBLY_MDB): $(ASSEMBLY)
$(ASSEMBLY): $(build_sources) $(build_resources) $(build_datafiles) $(DLL_REFERENCES) $(PROJECT_REFERENCES) $(build_xamlg_list) $(build_satellite_assembly_list)
	make pre-all-local-hook prefix=$(prefix)
	mkdir -p $(shell dirname $(ASSEMBLY))
	make $(CONFIG)_BeforeBuild
	$(ASSEMBLY_COMPILER_COMMAND) $(ASSEMBLY_COMPILER_FLAGS) -out:$(ASSEMBLY) -target:$(COMPILE_TARGET) $(build_sources_embed) $(build_resources_embed) $(build_references_ref)
	make $(CONFIG)_AfterBuild
	make post-all-local-hook prefix=$(prefix)

install-local: $(ASSEMBLY) $(ASSEMBLY_MDB)
	make pre-install-local-hook prefix=$(prefix)
	make install-satellite-assemblies prefix=$(prefix)
	mkdir -p '$(DESTDIR)$(libdir)/$(PACKAGE)'
	$(call cp,$(ASSEMBLY),$(DESTDIR)$(libdir)/$(PACKAGE))
	$(call cp,$(ASSEMBLY_MDB),$(DESTDIR)$(libdir)/$(PACKAGE))
	$(call cp,$(JAVAPI_DLL_MDB),$(DESTDIR)$(libdir)/$(PACKAGE))
	mkdir -p '$(DESTDIR)$(libdir)/pkgconfig'
	$(call cp,$(JAVAPI_CORE_PC),$(DESTDIR)$(libdir)/pkgconfig)
	make post-install-local-hook prefix=$(prefix)

uninstall-local: $(ASSEMBLY) $(ASSEMBLY_MDB)
	make pre-uninstall-local-hook prefix=$(prefix)
	make uninstall-satellite-assemblies prefix=$(prefix)
	$(call rm,$(ASSEMBLY),$(DESTDIR)$(libdir)/$(PACKAGE))
	$(call rm,$(ASSEMBLY_MDB),$(DESTDIR)$(libdir)/$(PACKAGE))
	$(call rm,$(JAVAPI_DLL_MDB),$(DESTDIR)$(libdir)/$(PACKAGE))
	$(call rm,$(JAVAPI_CORE_PC),$(DESTDIR)$(libdir)/pkgconfig)
	make post-uninstall-local-hook prefix=$(prefix)
